### PR TITLE
Get Pro status in managed LXD instance

### PR DESCRIPTION
**Pull request by linostar**
- [x] Have you followed the guidelines for contributing?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `tox`?

-----

### CODE REVIEW

**Comment by linostar** [comment]
@canonical/starcraft-reviewers This is ready.

**Review by lengau — COMMENTED** [review]
Could you add integration tests to this that check it with, say, Ubuntu Noble and Alma Linux 9?

**Comment by lengau** [comment]
@linostar I'm requesting an integration test like the ones here: https://github.com/canonical/craft-providers/blob/main/tests/integration/lxd/test_lxc.py

It would create an instance and run these functions on that instance.

**Review by tigarmo — APPROVED** [review]

**Review by lengau — APPROVED** [review]
Thanks @linostar , this looks good to me!

**Pull request merged**
