### PR TITLE
lxc: add has_image() helper and use yaml BaseLoader (CRAFT-144)

### PR DESCRIPTION
**Pull request by cjp256**
The image list data is a little complex for a caller to simply
check if an image is available.  This adds has_image() helper
to do that check.

While parsing image data, LXD tends to trip up Yaml's Loader
when parsing timestamps into datetime format. Use the BaseLoader
instead to avoid parsing timestamps (which may be invalid) and
simply keep them as strings.

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>

- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### CODE REVIEW

**Review by facundobatista — CHANGES_REQUESTED** [review]
Code looks fine, but we should add test cases for the "broken timestamp", so we're sure we won't come back to regular yaml parsing in the future.

**Comment by cjp256** [comment]
> Code looks fine, but we should add test cases for the "broken timestamp", so we're sure we won't come back to regular yaml parsing in the future.

Done!

**Review by cmatsuoka — APPROVED** [review]
Looks good!

**Review by facundobatista — APPROVED** [review]
Thanks!

**Pull request merged**
