### PR TITLE
Changes for 1.20.3

### PR DESCRIPTION
**Pull request by lengau**
- [x] Have you followed the guidelines for contributing?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `tox`?

-----

This is ready so we can do a rebase.

### CODE REVIEW

**Review by syu-w — APPROVED** [review]

**Review by mr-cal — COMMENTED** [review]
What do you think about bumping the compatibility tag to `v8`?

`v7` is used by 1.23, so theoretically someone could create an instance with `1.20.3`, upgrade to `1.23.x` and the same instance would be reused (which we don't want).

I'm happy to do a compatibility tag bump commit, [it's more tedious than it should be](https://github.com/canonical/craft-providers/issues/383) and I've gotten pretty quick at it.

**Comment by mr-cal** [comment]
> I've gotten pretty quick at it.

Meaning I run `git diff 69207f7~ 69207f7 --name-only | xargs sed -i 's/v6/v7/g'`

**Comment by lengau** [comment]
Thanks @mr-cal  - I missed the v7 in 1.23. I've updated to v8 now

**Review by mr-cal — APPROVED** [review]
Thanks!

**Comment by mr-cal** [comment]
Integration test failures are expected on this older branch. The tests are trying to launch 23.04 (lunar), which is no longer supported.

**Pull request merged**
