### PR TITLE
setup: uprev reqs and add type hint packages

### PR DESCRIPTION
**Pull request by cjp256**
Signed-off-by: Chris Patterson <chris.patterson@canonical.com>

- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### CODE REVIEW

**Comment by facundobatista** [comment]
Why? What do you need these new packages?

**Comment by cjp256** [comment]
The latest mypy switched to modular types from typeshed which meant installing the additional types-* packages.

https://mypy-lang.blogspot.com/2021/05/the-upcoming-switch-to-modular-typeshed.html

**Comment by cjp256** [comment]
If you're asking more generically why, it's just an occasional sync.  It  doesn't add any new pinned requirements for apps.

**Review by sergiusens — APPROVED** [review]

**Review by facundobatista — APPROVED** [review]
+1

**Pull request merged**
