### PR TITLE
tests: add a sudo marker for integration tests that require sudo

### LINKED ISSUE #222: lxd integration tests run`sudo lxd init`
The lxd integration tests call `LXD().init()`, which tries to initialize lxd with `sudo lxd init`:
https://github.com/canonical/craft-providers/blob/35bd3c49f3860a74f7f1f424873908581654d968/tests/unit/lxd/test_lxd.py#L32

This call should be removed or mocked out.

Reported in https://github.com/canonical/craft-providers/issues/131

### PR DESCRIPTION
**Pull request by lengau**
Fixes #222

- [ ] Have you followed the guidelines for contributing?
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `tox`?

-----

### CODE REVIEW

**Review by mr-cal — APPROVED** [review]

**Comment by mr-cal** [comment]
Can you add CRAFT_PROVIDERS_TESTS_ENABLE_SUDO to https://github.com/canonical/craft-providers/blob/7aacbfd60eb531f7969bdb2ac3971051df88a70f/.github/workflows/tests.yaml#L125 ?

**Comment by lengau** [comment]
@mr-cal can do, but my hope was that by testing for the `CI` environment variable we wouldn't need that. Do you want me to remove the `CI` test?

**Comment by mr-cal** [comment]
The test looks like it skipped:
```
tests/integration/lxd/test_lxd.py .s..s.                                 [ 19%]
```

But I tried it locally:
```
CI=1 pytest tests/integration/lxd/test_lxd.py -vv --setup-plan
```
and it looks like it does not skip those tests.


Aha!  I think it's because neither `CI` nor `CRAFT_PROVIDERS_TESTS_ENABLE_SUDO` get passed into the tox environment.

**Comment by mr-cal** [comment]
So how about using tox's `passenv` keyword for `CI`?

**Comment by lengau** [comment]
@mr-cal Aha good catch! Thank you! I've passed CI through, and I'm going to upstream that change into starbase as well

**Pull request merged**
