### PR TITLE
tests: re-enable alma linux integration tests

### LINKED ISSUE #502: Source alma and centos images
### What needs to get done

Create or find a new source for alma and centos images.

@sergiusens mentioned we can use people.canonical.com for this

We may also want to see if there is a canonical-driven initiative

### Why it needs to get done

Alma and centos images can no longer be fetched due to https://discuss.linuxcontainers.org/t/important-notice-for-lxd-users-image-server/18479

See https://chat.canonical.com/canonical/pl/eqsea5fznbf17c9bcd8mhg4m5a for context

### PR DESCRIPTION
**Pull request by mr-cal**
- [x] Have you followed the guidelines for contributing?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `tox`?

-----

See https://discourse.ubuntu.com/t/new-lxd-image-server-available-images-lxd-canonical-com/43824

Fixes #502

### CODE REVIEW

**Review by mattculler — APPROVED** [review]
Code looks good, I just have a workflow question: is there a reason why you put this on a new PR rather than #502?

**Comment by mr-cal** [comment]
> Code looks good, I just have a workflow question: is there a reason why you put this on a new PR rather than #502?

Good question - #502 is an issue and not a PR, so I can't make it a PR

**Comment by mattculler** [comment]
@mr-cal Oops!  Thanks!

**Review by lengau — APPROVED** [review]
Huzzah!

**Pull request merged**
