### PR TITLE
lxd: add buildd remote support (CRAFT-260)

### PR DESCRIPTION
**Pull request by cjp256**
Add configure_buildd_image_remote() helper to add the buildd
remote and return its name.  Calling applications will call
this as part of their setup code prior to launching
an instance.

Add launcher integration tests for the 16.04 and 18.04 buildd
images.  Xenial is currently unsupported because its
/etc/apt/sources.list does not include the -updates
or -security suites, breaking an assumption that snapd is updated
in the buildd image (it ships 2.0.2).  Further work will be
required to support it properly.

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>

- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

Requires #54 and #53 for integration tests to pass.

### CODE REVIEW

**Review by facundobatista — APPROVED** [review]
Looks great!

**Review by sergiusens — APPROVED** [review]
I do question the need for the remote, but this looks good, I would consider renaming the remote to something like "craft" so a user can quickly identify why it is there.

**Comment by cjp256** [comment]
> I do question the need for the remote, but this looks good, I would consider renaming the remote to something like "craft" so a user can quickly identify why it is there.

Renamed it to `craft-com.ubuntu.cloud-buildd`

**Comment by sergiusens** [comment]
that works, one test did not :-)

**Review by cmatsuoka — APPROVED** [review]

**Pull request merged**
