### PR TITLE
license: use LGPLv3 rather than GPLv3 (CRAFT-306)

### PR DESCRIPTION
**Pull request by cjp256**
As a library, LGPLv3 is more suitable than GPLv3.

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>

- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### CODE REVIEW

**Comment by cmatsuoka** [comment]
I think you'll need to updated the license notice in all individual files too.

**Comment by cjp256** [comment]
> I think you'll need to updated the license notice in all individual files too.

:facepalm: good point!

**Comment by cjp256** [comment]
Fixed!

**Review by sergiusens — APPROVED** [review]

**Review by cmatsuoka — APPROVED** [review]
Thanks! Don't forget to update the github project license as well.

**Review by sergiusens — CHANGES_REQUESTED** [review]
please remove "or later"

**Review by sergiusens — APPROVED** [review]

**Pull request merged**
